// ─────────────────────────────────────────────────────────────────
// GAME REGISTRY
// To add a new game:
//   1. Add an entry here
//   2. Create  src/games/YourGame.jsx
//   3. Add it to src/games/index.js
// That's it. Nothing else needs to change.
// ─────────────────────────────────────────────────────────────────

export const GAME_REGISTRY = [
  // ── Batch 1 — Original 5 ─────────────────────────────────────
  {
    id: "rps",
    title: "Rock Paper Scissors",
    description: "Classic hand battle. Outsmart the machine.",
    category: "Classic",
    icon: "✊",
    color: "#ff6b6b",
    glow: "rgba(255,107,107,0.4)",
    difficulty: "Easy",
    players: "1P",
    tags: ["classic", "luck", "quick"],
  },
  {
    id: "guess",
    title: "Guess the Number",
    description: "Crack the secret number with clever deduction.",
    category: "Puzzle",
    icon: "🔢",
    color: "#4ecdc4",
    glow: "rgba(78,205,196,0.4)",
    difficulty: "Medium",
    players: "1P",
    tags: ["puzzle", "logic", "numbers"],
  },
  {
    id: "dice",
    title: "Dice Roll",
    description: "Beat the house in a roll of fate.",
    category: "Luck",
    icon: "🎲",
    color: "#ffe66d",
    glow: "rgba(255,230,109,0.4)",
    difficulty: "Easy",
    players: "1P",
    tags: ["luck", "quick", "casual"],
  },
  {
    id: "tictactoe",
    title: "Tic Tac Toe",
    description: "Three in a row. Timeless strategy.",
    category: "Strategy",
    icon: "⬜",
    color: "#a29bfe",
    glow: "rgba(162,155,254,0.4)",
    difficulty: "Easy",
    players: "2P",
    tags: ["strategy", "classic", "2player"],
  },
  {
    id: "memory",
    title: "Memory Match",
    description: "Find all pairs before time runs out.",
    category: "Puzzle",
    icon: "🃏",
    color: "#fd79a8",
    glow: "rgba(253,121,168,0.4)",
    difficulty: "Hard",
    players: "1P",
    tags: ["puzzle", "memory", "cards"],
  },

  // ── Batch 2 ──────────────────────────────────────────────────
  {
    id: "snake",
    title: "Snake",
    description: "Eat. Grow. Don't bite yourself.",
    category: "Arcade",
    icon: "🐍",
    color: "#00b894",
    glow: "rgba(0,184,148,0.4)",
    difficulty: "Medium",
    players: "1P",
    tags: ["arcade", "reflex", "classic"],
  },
  {
    id: "whackamole",
    title: "Whack-a-Mole",
    description: "Smash every mole before it vanishes.",
    category: "Arcade",
    icon: "🔨",
    color: "#e17055",
    glow: "rgba(225,112,85,0.4)",
    difficulty: "Medium",
    players: "1P",
    tags: ["arcade", "reflex", "quick"],
  },
  {
    id: "wordjumble",
    title: "Word Jumble",
    description: "Unscramble the letters to find the hidden word.",
    category: "Puzzle",
    icon: "🔤",
    color: "#74b9ff",
    glow: "rgba(116,185,255,0.4)",
    difficulty: "Medium",
    players: "1P",
    tags: ["puzzle", "words", "brain"],
  },
  {
    id: "colorpicker",
    title: "Color Match",
    description: "Pick the exact hex color — pure eye training.",
    category: "Puzzle",
    icon: "🎨",
    color: "#fd9644",
    glow: "rgba(253,150,68,0.4)",
    difficulty: "Hard",
    players: "1P",
    tags: ["puzzle", "color", "brain"],
  },
  {
    id: "minesweeper",
    title: "Minesweeper",
    description: "Clear the field. One wrong move ends it all.",
    category: "Strategy",
    icon: "💣",
    color: "#b2bec3",
    glow: "rgba(178,190,195,0.4)",
    difficulty: "Hard",
    players: "1P",
    tags: ["strategy", "logic", "classic"],
  },
  {
    id: "typingspeed",
    title: "Typing Speed",
    description: "Race the clock. Every keystroke counts.",
    category: "Arcade",
    icon: "⌨️",
    color: "#55efc4",
    glow: "rgba(85,239,196,0.4)",
    difficulty: "Medium",
    players: "1P",
    tags: ["arcade", "reflex", "typing"],
  },
  {
    id: "mathblitz",
    title: "Math Blitz",
    description: "Solve equations fast before the timer explodes.",
    category: "Puzzle",
    icon: "➗",
    color: "#ffeaa7",
    glow: "rgba(255,234,167,0.4)",
    difficulty: "Medium",
    players: "1P",
    tags: ["puzzle", "math", "brain"],
  },
  {
    id: "simon",
    title: "Simon Says",
    description: "Mirror the pattern. How far can you go?",
    category: "Classic",
    icon: "🔵",
    color: "#0984e3",
    glow: "rgba(9,132,227,0.4)",
    difficulty: "Hard",
    players: "1P",
    tags: ["classic", "memory", "reflex"],
  },
  {
    id: "hangman",
    title: "Hangman",
    description: "Guess the word letter by letter. Don't hang.",
    category: "Classic",
    icon: "🪢",
    color: "#d63031",
    glow: "rgba(214,48,49,0.4)",
    difficulty: "Medium",
    players: "1P",
    tags: ["classic", "words", "logic"],
  },
  {
    id: "coinflip",
    title: "Coin Flip Streak",
    description: "Call heads or tails and build your streak.",
    category: "Luck",
    icon: "🪙",
    color: "#fdcb6e",
    glow: "rgba(253,203,110,0.4)",
    difficulty: "Easy",
    players: "1P",
    tags: ["luck", "quick", "casual"],
  },

  // ── Batch 3 ──────────────────────────────────────────────────
  {
    id: "breakout",
    title: "Breakout",
    description: "Bounce the ball. Smash every brick. Don't miss.",
    category: "Arcade",
    icon: "🧱",
    color: "#e84393",
    glow: "rgba(232,67,147,0.4)",
    difficulty: "Medium",
    players: "1P",
    tags: ["arcade", "reflex", "classic"],
  },
  {
    id: "higherlower",
    title: "Higher or Lower",
    description: "Is the next card higher or lower? Build your streak.",
    category: "Luck",
    icon: "🃏",
    color: "#a8e063",
    glow: "rgba(168,224,99,0.4)",
    difficulty: "Easy",
    players: "1P",
    tags: ["luck", "cards", "quick"],
  },
  {
    id: "reactiontime",
    title: "Reaction Time",
    description: "Hit the button the instant it lights up. Fast fingers only.",
    category: "Arcade",
    icon: "⚡",
    color: "#f9ca24",
    glow: "rgba(249,202,36,0.4)",
    difficulty: "Medium",
    players: "1P",
    tags: ["arcade", "reflex", "speed"],
  },
  {
    id: "countmaster",
    title: "Count Master",
    description: "Count the dots faster than the timer. No cheating.",
    category: "Puzzle",
    icon: "🔵",
    color: "#6c5ce7",
    glow: "rgba(108,92,231,0.4)",
    difficulty: "Medium",
    players: "1P",
    tags: ["puzzle", "brain", "numbers"],
  },
  {
    id: "passwordgen",
    title: "Password Guesser",
    description: "Crack the 4-digit code with Mastermind logic.",
    category: "Puzzle",
    icon: "🔐",
    color: "#00cec9",
    glow: "rgba(0,206,201,0.4)",
    difficulty: "Hard",
    players: "1P",
    tags: ["puzzle", "logic", "deduction"],
  },
  {
    id: "wordchain",
    title: "Word Chain",
    description: "Each word must start with the last letter of the previous.",
    category: "Classic",
    icon: "🔗",
    color: "#fd79a8",
    glow: "rgba(253,121,168,0.4)",
    difficulty: "Medium",
    players: "1P",
    tags: ["classic", "words", "brain"],
  },
  {
    id: "spacebattle",
    title: "Space Battle",
    description: "Dodge asteroids. Survive as long as you can.",
    category: "Arcade",
    icon: "🚀",
    color: "#74b9ff",
    glow: "rgba(116,185,255,0.4)",
    difficulty: "Hard",
    players: "1P",
    tags: ["arcade", "reflex", "space"],
  },
  {
    id: "trivia",
    title: "Trivia Blitz",
    description: "Answer random trivia questions before time runs out.",
    category: "Puzzle",
    icon: "🧠",
    color: "#00b894",
    glow: "rgba(0,184,148,0.4)",
    difficulty: "Medium",
    players: "1P",
    tags: ["puzzle", "trivia", "brain"],
  },
  {
    id: "speedclick",
    title: "Speed Click",
    description: "Click as many targets as possible in 10 seconds.",
    category: "Arcade",
    icon: "🎯",
    color: "#ff7675",
    glow: "rgba(255,118,117,0.4)",
    difficulty: "Easy",
    players: "1P",
    tags: ["arcade", "reflex", "quick"],
  },
  {
    id: "sequencepush",
    title: "Sequence Push",
    description: "Remember and repeat the growing number sequence.",
    category: "Classic",
    icon: "🔢",
    color: "#ffeaa7",
    glow: "rgba(255,234,167,0.4)",
    difficulty: "Hard",
    players: "1P",
    tags: ["classic", "memory", "numbers"],
  },

  // ── Batch 4 ──────────────────────────────────────────────────
  {
    id: "pong",
    title: "Pong",
    description: "Rally the ball. First to miss loses the point.",
    category: "Arcade",
    icon: "🏓",
    color: "#00cec9",
    glow: "rgba(0,206,201,0.4)",
    difficulty: "Medium",
    players: "1P",
    tags: ["arcade", "classic", "reflex"],
  },
  {
    id: "anagram",
    title: "Anagram Hunt",
    description: "Rearrange all the letters into the right word.",
    category: "Puzzle",
    icon: "🔡",
    color: "#e17055",
    glow: "rgba(225,112,85,0.4)",
    difficulty: "Medium",
    players: "1P",
    tags: ["puzzle", "words", "brain"],
  },
  {
    id: "binaryflip",
    title: "Binary Flip",
    description: "Convert the binary number to decimal. Think fast.",
    category: "Puzzle",
    icon: "💻",
    color: "#00b894",
    glow: "rgba(0,184,148,0.4)",
    difficulty: "Hard",
    players: "1P",
    tags: ["puzzle", "math", "numbers"],
  },
  {
    id: "gridpaint",
    title: "Grid Paint",
    description: "Mirror the target pattern on an empty grid.",
    category: "Puzzle",
    icon: "🖼️",
    color: "#fd79a8",
    glow: "rgba(253,121,168,0.4)",
    difficulty: "Easy",
    players: "1P",
    tags: ["puzzle", "visual", "brain"],
  },
  {
    id: "blackjack",
    title: "Blackjack",
    description: "Hit or stand. Beat the dealer without going bust.",
    category: "Luck",
    icon: "🂡",
    color: "#fdcb6e",
    glow: "rgba(253,203,110,0.4)",
    difficulty: "Medium",
    players: "1P",
    tags: ["luck", "cards", "strategy"],
  },
  {
    id: "slidepuzzle",
    title: "Slide Puzzle",
    description: "Slide the tiles into the correct order.",
    category: "Puzzle",
    icon: "🧩",
    color: "#a29bfe",
    glow: "rgba(162,155,254,0.4)",
    difficulty: "Hard",
    players: "1P",
    tags: ["puzzle", "logic", "classic"],
  },
  {
    id: "colorsequence",
    title: "Color Sequence",
    description: "Tap the colors in the exact order they flashed.",
    category: "Classic",
    icon: "🌈",
    color: "#ff7675",
    glow: "rgba(255,118,117,0.4)",
    difficulty: "Medium",
    players: "1P",
    tags: ["classic", "memory", "reflex"],
  },
  {
    id: "typeracer",
    title: "Type Racer",
    description: "Race against the ghost. Type faster than your best.",
    category: "Arcade",
    icon: "🏎️",
    color: "#55efc4",
    glow: "rgba(85,239,196,0.4)",
    difficulty: "Hard",
    players: "1P",
    tags: ["arcade", "typing", "speed"],
  },
  {
    id: "catchdrop",
    title: "Catch & Drop",
    description: "Move the basket. Catch fruits, dodge bombs.",
    category: "Arcade",
    icon: "🧺",
    color: "#f9ca24",
    glow: "rgba(249,202,36,0.4)",
    difficulty: "Medium",
    players: "1P",
    tags: ["arcade", "reflex", "quick"],
  },
  {
    id: "oddoneout",
    title: "Odd One Out",
    description: "Find the one tile that doesn't match the others.",
    category: "Puzzle",
    icon: "🔍",
    color: "#74b9ff",
    glow: "rgba(116,185,255,0.4)",
    difficulty: "Easy",
    players: "1P",
    tags: ["puzzle", "visual", "quick"],
  },
];

export const CATEGORIES = ["All", "Classic", "Puzzle", "Luck", "Strategy", "Arcade"];
